"""
Simplified LLM endpoints for development/demo purposes.
Uses report_llm_client (Falcon/FinGPT/Llama) for real report text when configured.
"""

import os
from typing import List, Dict, Any, Optional
from fastapi import APIRouter, Body
from datetime import datetime

from src.llm.report_llm_client import generate_report_text as llm_generate_report_text

llm_router = APIRouter()

# Report-type prompts for AI generation
REPORT_PROMPTS = {
    "market_summary": (
        "Write a concise one-page market analysis report for the past week. "
        "Cover major equity indices, tech sector momentum, and key macro drivers. "
        "Use clear sections: Summary, Equity Markets, Risks, and Outlook. "
        "Write in professional, neutral tone."
    ),
    "risk_assessment": (
        "Write a short risk assessment report for a diversified portfolio. "
        "Include: volatility outlook, correlation risks, tail-risk considerations, "
        "and 2–3 concrete risk-management recommendations. Professional tone."
    ),
    "sentiment": (
        "Write a brief market sentiment report based on social and news sentiment. "
        "Include: overall sentiment score, sector highlights, and any sentiment divergences. "
        "One page, professional tone."
    ),
    "technical": (
        "Write a short technical analysis report. Cover key support/resistance levels, "
        "momentum indicators, and 2–3 actionable technical signals. Professional tone."
    ),
}
DEFAULT_PROMPT = (
    "Write a concise one-page financial market report covering recent price action, "
    "key drivers, and a brief outlook. Use clear sections and professional tone."
)


@llm_router.get("/status")
async def get_llm_status() -> Dict[str, Any]:
    """
    Return which LLM backends are configured (no secrets).
    Used by the UI to show an LLM status indicator.
    """
    llama = bool(os.getenv("LLAMA_URL", "").strip())
    falcon = bool(os.getenv("FALCON_TGI_URL", "").strip())
    fingpt_local = bool(os.getenv("FINGPT_LOCAL_URL", "").strip())
    hf_token = bool(os.getenv("HF_TOKEN", "").strip())
    any_configured = llama or falcon or fingpt_local or hf_token
    return {
        "llama_configured": llama,
        "falcon_configured": falcon,
        "fingpt_local_configured": fingpt_local,
        "hf_configured": hf_token,
        "any_configured": any_configured,
    }


@llm_router.get("/reports/analysis-status")
async def get_analysis_status():
    """
    Get the status of various analysis components
    """
    return {
        "sections": [
            {"id": "market", "name": "Market Analysis", "status": "completed", "progress": 100, "insights": 8, "lastUpdated": "2 min ago"},
            {"id": "portfolio", "name": "Portfolio Performance", "status": "completed", "progress": 100, "insights": 12, "lastUpdated": "5 min ago"},
            {"id": "risk", "name": "Risk Assessment", "status": "processing", "progress": 75, "insights": 6, "lastUpdated": "1 min ago"},
            {"id": "sentiment", "name": "Sentiment Analysis", "status": "completed", "progress": 100, "insights": 15, "lastUpdated": "3 min ago"},
            {"id": "technical", "name": "Technical Signals", "status": "processing", "progress": 60, "insights": 9, "lastUpdated": "Now"},
            {"id": "macro", "name": "Macro Environment", "status": "pending", "progress": 0, "insights": 0, "lastUpdated": "Pending"}
        ]
    }

@llm_router.get("/reports/data-sources")
async def get_data_sources():
    """
    Get the status of data sources feeding into AI analysis
    """
    return {
        "sources": [
            {"id": "market", "name": "Market Data Feed", "type": "market_data", "status": "active", "lastSync": "30s ago", "recordsProcessed": 15420},
            {"id": "news", "name": "News Analytics", "type": "news", "status": "active", "lastSync": "1m ago", "recordsProcessed": 2847},
            {"id": "social", "name": "Social Sentiment", "type": "social", "status": "active", "lastSync": "45s ago", "recordsProcessed": 8932},
            {"id": "technical", "name": "Technical Indicators", "type": "technical", "status": "active", "lastSync": "15s ago", "recordsProcessed": 5621},
            {"id": "fundamental", "name": "Fundamental Data", "type": "fundamental", "status": "active", "lastSync": "2m ago", "recordsProcessed": 1205},
            {"id": "sentiment", "name": "Sentiment Engine", "type": "sentiment", "status": "active", "lastSync": "20s ago", "recordsProcessed": 3847}
        ]
    }

@llm_router.post("/reports/generate-insights")
async def generate_ai_insights(
    body: Optional[Dict[str, Any]] = Body(default=None),
):
    """
    Generate AI-powered insights. When LLM is configured (Falcon/FinGPT/Llama),
    the report narrative is generated by the model; otherwise returns simulated content.
    """
    report_type = (body or {}).get("report_type") or "market_summary"
    symbols = (body or {}).get("symbols")  # optional list of symbols for context
    prompt = REPORT_PROMPTS.get(report_type, DEFAULT_PROMPT)
    if symbols:
        prompt = f"Assets of interest: {', '.join(symbols[:10])}.\n\n{prompt}"

    raw_text, model_used = await llm_generate_report_text(prompt, max_new_tokens=1024)
    if not raw_text:
        raw_text = (
            "Market analysis shows strong bullish momentum in tech sector with "
            "emerging opportunities in commodities. Risk management protocols recommend "
            "maintaining diversified exposure while monitoring crypto volatility signals."
        )

    insights = [
        {
            "id": "tech_momentum",
            "type": "bullish",
            "title": "Strong Momentum in Tech Sector",
            "summary": "AI analysis indicates sustained upward pressure in NVDA (+12.34), MSFT, and GOOGL based on earnings momentum, institutional flow, and technical patterns. Expected 12-15% upside over next 30 days.",
            "confidence": 87,
            "impact": "high",
            "sources": ["Technical Analysis", "Market Data", "News Sentiment", "Options Flow"],
            "timestamp": datetime.now().isoformat(),
            "ai_analysis": "Technical momentum indicators show strong bullish signals across major tech stocks with institutional accumulation patterns."
        },
        {
            "id": "crypto_volatility",
            "type": "warning",
            "title": "Crypto Volatility Alert",
            "summary": "Unusual options activity and social sentiment divergence detected in BTC-USD and ETH-USD. Potential 20-25% volatility spike expected within 48-72 hours.",
            "confidence": 78,
            "impact": "medium",
            "sources": ["Social Sentiment", "Options Data", "Technical Indicators"],
            "timestamp": datetime.now().isoformat(),
            "ai_analysis": "AI detects mixed signals in crypto markets with institutional accumulation conflicting with retail sentiment."
        },
        {
            "id": "commodities_rotation",
            "type": "opportunity",
            "title": "Commodities Rotation Signal",
            "summary": "Inflation hedge rotation detected. GLD and SLV showing strong accumulation patterns while institutional money rotates from growth to value. 8-12% upside potential.",
            "confidence": 82,
            "impact": "medium",
            "sources": ["Institutional Flow", "Macro Analysis", "Technical Patterns"],
            "timestamp": datetime.now().isoformat(),
            "ai_analysis": "Macro environment favors precious metals as inflation hedge with central bank policy uncertainty."
        }
    ]

    model_label = {
        "llama": "Llama (Ollama)",
        "falcon": "Falcon (TGI)",
        "fingpt_local": "FinGPT (local)",
        "fingpt_hf": "FinGPT (HuggingFace)",
        "simulated": "Simulated (no LLM configured)",
    }.get(model_used, model_used)

    return {
        "insights": insights,
        "market_summary": {
            "total_assets_analyzed": 17,
            "bullish_signals": 12,
            "bearish_signals": 4,
            "neutral_signals": 1,
            "analysis_timestamp": datetime.now().isoformat(),
            "ai_model": model_label,
        },
        "raw_ai_response": raw_text,
        "model_used": model_used,
        "report_type": report_type,
    }

@llm_router.post("/finetune")
async def start_finetuning(output_dir: str = "./peft-output"):
    """
    Mock fine-tuning endpoint
    """
    return {
        "task_id": f"ft_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
        "status": "started",
        "message": "Fine-tuning job initiated (mock mode)",
        "output_dir": output_dir
    }

@llm_router.get("/finetune/{task_id}")
async def get_finetuning_status(task_id: str):
    """
    Mock fine-tuning status endpoint
    """
    return {
        "task_id": task_id,
        "status": "completed",
        "progress": 100,
        "message": "Fine-tuning completed successfully (mock mode)",
        "model_path": "./peft-output",
        "metrics": {
            "loss": 0.234,
            "eval_loss": 0.267,
            "perplexity": 12.45
        }
    }

@llm_router.post("/predict")
async def predict(text: str):
    """
    Mock prediction endpoint
    """
    return {
        "prediction": f"AI Analysis: Based on the input '{text[:50]}...', the market sentiment appears optimistic with moderate confidence.",
        "confidence": 0.75,
        "model": "octopus-financial-llm-mock"
    }

@llm_router.post("/llama/predict")
async def predict_llama(text: str):
    """
    Mock Llama prediction endpoint
    """
    return {
        "response": f"Financial Analysis: {text[:100]}... Based on current market conditions, I recommend a balanced approach with emphasis on risk management and diversification.",
        "model": "llama-financial-mock",
        "timestamp": datetime.now().isoformat()
    } 